module.exports = {
  printWidth: 80,
  tabWidth: 2,
  useTabs: false,
  semi: false,
  singleQuote: false,
  quoteProps: "as-needed",
  jsxSingleQuote: false,
  trailingComma: "all",
  bracketSpacing: true,
  jsxBracketSameLine: false,
  arrowParens: "avoid",
  parser: "babel-ts",
  requirePragma: false,
  insertPragma: false,
  proseWrap: "preserve",
  endOfLine: "auto",
  vueIndentScriptAndStyle: true,
  htmlWhitespaceSensitivity: "strict",
}
